### PR TITLE
Order Book API update

### PR DESCRIPTION
**Pull request by jelilat**
The postMarketOrder function has been updated with postProMarketOrder from the new [order books](https://developers.buycoins.africa/orderbook-trading/post-market-order) API

getMarketOrders has also been updated with the [Stream Orderbook ](https://developers.buycoins.africa/orderbook-trading/stream-order-book)endpoint.

recurring-buy.js was updated to reflect both changes @ireade

### CODE REVIEW

**Comment by jelilat** [comment]
@ireade

**Review by ireade — APPROVED** [review]

**Comment by alephile** [comment]
@jelilat you didn't merge after Ire's approval. You can next time. I will merge now. @ireade please let us know if it works tomorrow/day after.

**Comment by ireade** [comment]
@jelilat didn't work today, there was actually no transaction in my history either so there's probably a bug somewhere

**Comment by jelilat** [comment]
@ire I'll do some testing today and try to find out what the issue is

**Pull request merged**
